# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 500)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setStyleSheet("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 0, 500, 30))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.team_cbox = QtWidgets.QComboBox(Dialog)
        self.team_cbox.setGeometry(QtCore.QRect(140, 50, 121, 31))
        self.team_cbox.setStyleSheet("border: 1px ridge black;")
        self.team_cbox.setEditable(False)
        self.team_cbox.setCurrentText("")
        self.team_cbox.setObjectName("team_cbox")
        self.team_clabel = QtWidgets.QLabel(Dialog)
        self.team_clabel.setGeometry(QtCore.QRect(140, 50, 103, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.team_clabel.setFont(font)
        self.team_clabel.setStyleSheet("background-color:white;\n"
                                        "border: 1px ridge black;")
        self.team_clabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.team_clabel.setObjectName("team_clabel")
        self.match_clabel = QtWidgets.QLabel(Dialog)
        self.match_clabel.setGeometry(QtCore.QRect(540, 50, 103, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.match_clabel.setFont(font)
        self.match_clabel.setStyleSheet("background-color:white;\n"
                                        "border: 1px ridge black;")
        self.match_clabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.match_clabel.setObjectName("match_clabel")
        self.match_cbox = QtWidgets.QComboBox(Dialog)
        self.match_cbox.setGeometry(QtCore.QRect(540, 50, 121, 31))
        self.match_cbox.setStyleSheet("border: 1px ridge black;")
        self.match_cbox.setEditable(False)
        self.match_cbox.setCurrentText("")
        self.match_cbox.setObjectName("match_cbox")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(60, 110, 681, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(100, 150, 90, 30))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.player_list = QtWidgets.QListWidget(Dialog)
        self.player_list.setGeometry(QtCore.QRect(100, 180, 211, 301))
        self.player_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.player_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.player_list.setObjectName("player_list")
        self.points_list = QtWidgets.QListWidget(Dialog)
        self.points_list.setGeometry(QtCore.QRect(480, 180, 211, 301))
        self.points_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.points_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.points_list.setObjectName("points_list")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(480, 150, 90, 30))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.points_label = QtWidgets.QLabel(Dialog)
        self.points_label.setGeometry(QtCore.QRect(570, 150, 90, 30))
        self.points_label.setStyleSheet("color:blue;")
        self.points_label.setText("")
        self.points_label.setObjectName("points_label")
        self.label.raise_()
        self.team_cbox.raise_()
        self.team_clabel.raise_()
        self.match_cbox.raise_()
        self.match_clabel.raise_()
        self.line.raise_()
        self.label_2.raise_()
        self.player_list.raise_()
        self.points_list.raise_()
        self.label_5.raise_()
        self.points_label.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Evaluate the perfomance of your team"))
        self.team_clabel.setText(_translate("Dialog", "Select Team"))
        self.match_clabel.setText(_translate("Dialog", "Select Match"))
        self.label_2.setText(_translate("Dialog", "Players"))
        self.label_5.setText(_translate("Dialog", "Points"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
